name: Latest X post workflow
on:
  schedule: # Run workflow automatically
    - cron: '2 */2 * * *' # Runs every 2 hours, at the 2nd minute (to capture X posts that happen right on the hour)
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write
  actions: write

jobs:
  update-readme-with-posts:
    name: Update this repo's README with latest X posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in X posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "6"
          feed_list: "https://bsky.app/profile/did:plc:w2gemkuyjfxa3whvwixnzihz/rss"
          template: |
            - $description<br/><br/>
      - name: Remove https://github.com suffix
        run: |
          # Delete any line that contains ONLY the URL + <br/><br/> (if any)
          sed -i '/^https:\/\/github\.com\s*<br\/><br\/>$/d' README.md
      
          # Remove URL + trailing <br/>s if followed by END marker or end of line
          sed -i 's#https://github\.com\(\s*<[/]\?br\s*/?>\)*\(<!-- BLOG-POST-LIST:END -->\|\s*$\)##g' README.md
      - name: Debug README snippet
        run: tail -40 README.md
      - name: Commit and push cleaned README
        run: |
          git config user.name "jingeno"
          git config user.email "jingeno@users.noreply.github.com"
          git add README.md
          git commit -m "Updated README.md with latest X posts" || echo "Nothing to commit"
          git push
