name: Latest X post workflow
on:
  schedule: # Run workflow automatically
    - cron: '2 */2 * * *' # Runs every 2 hours, at the 2nd minute (to capture X posts that happen right on the hour)
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write
  actions: write

jobs:
  update-readme-with-posts:
    name: Update this repo's README with latest X posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in X posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          feed_list: "https://bsky.app/profile/did:plc:w2gemkuyjfxa3whvwixnzihz/rss"
          commit_message: Updated with my latest X posts
          committer_username: jingeno
          committer_email: jingeno@users.noreply.github.com
          template: |
            - $description<br/><br/>

      - name: Remove https://github.com suffix with flexible br tags
        run: |
          sed -i 's|https://github\.com<br/><br/>|<br/><br/>|g' README.md

      - name: Remove https://youtube.com suffix with flexible br tags
        run: |
          sed -i 's|https://youtube\.com<br/><br/>|<br/><br/>|g' README.md

      - name: Remove empty description entries
        run: |
          sed -i 's/- <br\/><br\/>//g' README.md
          
      - name: Commit and push cleaned README
        run: |
          git config user.name "jingeno"
          git config user.email "jingeno@users.noreply.github.com"
          git add README.md
          git commit -m "Cleaned up README posts" || echo "Nothing to commit"
          git pushit -S -m "Cleaned up README posts" || echo "Nothing to commit"
          git push
