name: Latest X post workflow
on:
  schedule: # Run workflow automatically
    - cron: '2 */2 * * *' # Runs every 2 hours, at the 2nd minute (to capture X posts that happen right on the hour)
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write
  actions: write

jobs:
  update-readme-with-posts:
    name: Update this repo's README with latest X posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Git user for committing
        run: |
          git config --global user.name "jingeno"
          git config --global user.email "joe.ingeno@protonmail.com"
      - name: Pull in X posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://bsky.app/profile/did:plc:w2gemkuyjfxa3whvwixnzihz/rss"
          template: |
            - $description<br/><br/>
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
