name: Latest X post workflow
on:
  schedule: # Run workflow automatically
    - cron: '2 */2 * * *' # Runs every 2 hours, at the 2nd minute (to capture X posts that happen right on the hour)
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write
  actions: write

jobs:
  update-readme-with-posts:
    name: Update this repo's README with latest X posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH signing key
        env:
          SSH_SIGNING_KEY: ${{ secrets.SSH_SIGNING_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_SIGNING_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub
          git config --global gpg.format ssh
          git config --global user.signingkey ~/.ssh/id_ed25519.pub
          git config --global commit.gpgsign true

      - name: Pull in X posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "6"
          feed_list: "https://bsky.app/profile/did:plc:w2gemkuyjfxa3whvwixnzihz/rss"
          commit_message: Updated with my latest X posts
          committer_username: jingeno
          committer_email: jingeno@users.noreply.github.com
          template: |
            - $description<br/><br/>

      - name: Remove https://github.com suffix with flexible br tags
        run: |
          sed -i 's|https://github\.com<br/><br/>|<br/><br/>|g' README.md

      - name: Commit and push cleaned README (signed)
        run: |
          git config user.name "jingeno"
          git config user.email "jingeno@users.noreply.github.com"
          git add README.md
          git commit -S -m "Removed unnecessary github.com link(s)" || echo "Nothing to commit"
          git push
